algoritmo "ProcedOl·Mundo"

var
   c : caractere

procedimento Gerador(a : caractere)
inicio
      EscrevaL("+-------=======------+")
      EscrevaL("+------Ol· Mundo-----+")
      EscrevaL("+-------=======------+")


fimProcedimento

inicio

      Gerador(c)
      Gerador(c)
      Gerador(c)
      Gerador(c)
      Gerador(c)
      Gerador(c)
      Gerador(c)
      Gerador(c)
      Gerador(c)
      Gerador(c)
      Gerador(c)

fimalgoritmo
