algoritmo "rotina"

var
     n1,n2 : Inteiro

Procedimento Soma(A, B : Inteiro)

inicio
       EscrevaL("Você digitou n1 = ", A)
       EscrevaL("Você digitou n2 = ", B)
       EscrevaL("A soma deles vale: ", A + B)

fimProcedimento

inicio

      EscrevaL("Digite um valor: ")
      Leia(n1)
      EscrevaL("Digite um valor: ")
      Leia(n2)
      Soma(n1, n2)

fimalgoritmo
